const byId = (id) => document.getElementById(id);

export const dom = {
  workspace: byId('workspace'),
  dropzone: byId('dropzone'),
  dropzoneBtn: byId('dropzoneBtn'),
  openBtn: byId('openBtn'),
  helpBtn: byId('helpBtn'),
  helpOverlay: byId('helpOverlay'),
  helpClose: byId('helpClose'),
  fileChip: byId('fileChip'),
  fileName: byId('fileName'),
  imageDims: byId('imageDims'),

  stage: byId('stage'),
  canvasLayer: byId('canvasLayer'),
  img: byId('img'),
  stageOutline: byId('stageOutline'),
  marker: byId('marker'),
  guideH: document.querySelector('.guide-h'),
  guideV: document.querySelector('.guide-v'),
  loupe: byId('loupe'),
  zoomBadge: byId('zoomBadge'),
  liveRegion: byId('liveRegion'),

  panel: byId('panel'),
  previewTile: document.querySelector('.preview-tile'),
  previewFrame: byId('previewFrame'),
  previewImg: byId('previewImg'),
  previewOutline: byId('previewOutline'),
  previewOrigin: byId('previewOrigin'),
  previewPlay: byId('previewPlay'),
  previewStage: byId('previewStage'),
  presetRow: byId('presetRow'),
  customSliders: byId('customSliders'),
  previewScale: byId('previewScale'),
  previewScaleInput: byId('previewScaleInput'),
  previewRotate: byId('previewRotate'),
  previewRotateInput: byId('previewRotateInput'),

  xInput: byId('xInput'),
  yInput: byId('yInput'),
  unitToggle: byId('unitToggle'),
  grid9: byId('grid9'),
  stepToggle: byId('stepToggle'),
  stepLabel: byId('stepLabel'),
  snapToggle: byId('snapToggle'),
  loupeToggle: byId('loupeToggle'),
  undoBtn: byId('undoBtn'),
  redoBtn: byId('redoBtn'),

  cssOut: byId('cssOut'),
  copyBtn: byId('copyBtn'),
  copyValueBtn: byId('copyValueBtn'),
  precisionBtn: byId('precisionBtn'),
  autoCopyToggle: byId('autoCopyToggle'),
  templateInput: byId('templateInput'),

  pins: byId('pins'),
  resetBtn: byId('resetBtn'),
  toast: byId('toast'),
};
